### ISSUE TITLE
Add CI to validate the enterprise chart

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo-mesh-enterprise-helm#21]
We should add a CI check to verify that all components in this chart depend on the same version of the open source Gloo Mesh repo.

**Comment by ilackarms** [comment]
One possible approach would be to export the e2e tests from the OSS and GME repos as public functions, and allow them to be imported to the GMEH repo. 

the only variable we should have to configure is how the GME components are deployed during the `setup-kind` script. we can solve this by parameterizing. 

in OSS/GME, the component images and charts are built pushed and deployed individually, from source. 

in GMEH, the component images and charts will have already been released; we can simply build the chart with bumped versions locally (in CI), deploy from there, then run all the OSS / GME tests.
